### ISSUE TITLE
[request] Bump to v1.4.7

### ISSUE THREAD

**Issue by runlevel5** [BrycensRanch/gpu-screen-recorder-git-copr#4]
The v1.4.7 is already out. It would be great if you could bump this up

**Comment by BrycensRanch** [comment]
Hi! This COPR doesn't build on my machine and I never got it to that state since I was just learning about packaging. I am going to update it though since you're interested.

**Comment by BrycensRanch** [comment]
The builds are now passing and multiple RPM distros such as Fedora, Mageia, and OpenSUSE TW are supported. Additionally EPEL 9 is supported. EPEL 10 I'm working on it and investigating OpenSUSE Leap build failures for the future. Enjoy using the COPR! 😁
